# Generated by Django 4.1.1 on 2023-04-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='deegre',
            new_name='degree',
        ),
    ]
