# Generated by Django 4.1.1 on 2023-04-12 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_file_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='files',
        ),
        migrations.AlterField(
            model_name='file',
            name='fille',
            field=models.FileField(upload_to='img_cours/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fils', to='course.lessons'),
        ),
    ]
