# Generated by Django 4.1.1 on 2023-04-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.AddField(
            model_name='student',
            name='password2',
            field=models.CharField(default='0', max_length=123),
        ),
    ]
